### ISSUE TITLE
Soul charm crash

### ISSUE THREAD

**Issue by Kuggle01** [chronosacaria/MCDungonesArtifacts#16]
https://paste.ee/p/a8U44 I got a crash after using the soul charm in a large group of enemies, this has completely bricked my world and rendered it unplayable, as it will always crash once loaded

**Comment by chronosacaria** [comment]
Please read the log. This has nothing to do with MCDAR. 

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.0.1-jre.jar:?]
	at me.sandbox.entity.AlchemistEntity.cancelEffect(AlchemistEntity.java:140) ~[illager_expansion-0.1.5.jar:?]
	at me.sandbox.entity.AlchemistEntity.removeEffectsinCloud(AlchemistEntity.java:150) ~[illager_expansion-0.1.5.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at me.sandbox.entity.AlchemistEntity.method_5958(AlchemistEntity.java:189) ~[illager_expansion-0.1.5.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:759) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2609) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:546) ~[client-intermediary.jar:?]
	at net.minecraft.class_1588.method_6007(class_1588.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3763.method_6007(class_3763.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2354) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:346) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:702) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:485) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907) ~[client-intermediary.jar:?]
	... 5 more
```

**Comment by chronosacaria** [comment]
As this crash has nothing to do with MCDAR, this issue will be closed.
