### ISSUE TITLE
Tasty Bone is Unusable in Medieval Minecraft Modpack due to Duplicate ID Value

### ISSUE THREAD

**Issue by chronosacaria** [chronosacaria/MCDungonesArtifacts#20]
What is output to the console when using the Tasty Bone in Medieval Minecraft Modpack
```
[09:03:58] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket@5b8feb2a, suppressing error
java.lang.IllegalArgumentException: Duplicate id value for 26!
	at net.minecraft.entity.data.DataTracker.startTracking(DataTracker.java:82) ~[client-intermediary.jar:?]
	at chronosacaria.mcdar.entities.TastyBoneWolfEntity.initDataTracker(TastyBoneWolfEntity.java:42) ~[mcdar-1.5.0.jar:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:292) ~[client-intermediary.jar:?]
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.entity.mob.MobEntity.<init>(MobEntity.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.entity.mob.PathAwareEntity.<init>(PathAwareEntity.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.entity.passive.PassiveEntity.<init>(PassiveEntity.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.entity.passive.AnimalEntity.<init>(AnimalEntity.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.entity.passive.TameableEntity.<init>(TameableEntity.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.entity.passive.WolfEntity.<init>(WolfEntity.java:100) ~[client-intermediary.jar:?]
	at chronosacaria.mcdar.entities.TastyBoneWolfEntity.<init>(TastyBoneWolfEntity.java:30) ~[mcdar-1.5.0.jar:?]
	at net.minecraft.entity.EntityType.create(EntityType.java:487) ~[client-intermediary.jar:?]
	at chronosacaria.mcdar.api.SummoningHelper.summonTastyBoneWolf(SummoningHelper.java:106) ~[mcdar-1.5.0.jar:?]
	at chronosacaria.mcdar.artefacts.TastyBoneItem.useOnBlock(TastyBoneItem.java:33) ~[mcdar-1.5.0.jar:?]
	at net.minecraft.item.ItemStack.useOnBlock(ItemStack.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager.java:355) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler.java:1145) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by bmezhibovskiy** [comment]
I am also getting this. Can we make the ID's configurable?

**Comment by chronosacaria** [comment]
Incompatible mod set, at this time. This issue shall be closed for the time being
