### ISSUE TITLE
Curseforge: Mod listed as compatible with 1.16.3, requires 1.16.5

### ISSUE THREAD

**Issue by Derpford** [chronosacaria/MCDungonesArtifacts#3]
```
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mcdar requires {minecraft @ [1.16.5]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195)
	... 5 more
```

![image](https://user-images.githubusercontent.com/10187719/125008085-59cebf00-e027-11eb-84f3-80779882d0d3.png)

This is causing problems, as I'm trying to load mods via Curseforge, and Curseforge's launcher is helpfully listing MCD Artifacts as compatible with 1.16.3 even though the mod has a version check for 1.16.5.

**Comment by chronosacaria** [comment]
Thanks for bringing that to my attention. I've fixed it on CurseForge so that should fix that in the launcher. There was a point at which it was not compatible with 1.16.3 and 1.16.4 because of a bug that I didn't realise was there, but I fixed it pretty quickly but I guess I never updated the CurseForge page when I found the bug.
