### ISSUE TITLE
[Bug Report]: Iron Golem Spawner Entity Ticking Crash

### ISSUE THREAD

**Issue by jacobcrashout** [chronosacaria/MCDungonesArtifacts#45]
### Describe the bug; What happened?

I am using Fabric on version 1.20.1, I reported this on curseforge a few days ago, here is a full log of the crash report:

Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_19538()" because "$$0" is null
	at knot//net.minecraft.class_1297.method_5858(class_1297.java:1579)
	at knot//chronosacaria.mcdar.goals.FollowSummonerGoal.method_6266(FollowSummonerGoal.java:41)
	at knot//net.minecraft.class_4135.method_6266(class_4135.java:27)
	at knot//net.minecraft.class_1355.method_6275(class_1355.java:85)
	at knot//net.minecraft.class_1308.method_6023(class_1308.java:771)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:550)
	at knot//net.minecraft.class_1439.method_6007(class_1439.java:121)
	at knot//chronosacaria.mcdar.entities.GolemKitGolemEntity.method_6007(GolemKitGolemEntity.java:68)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_1297.method_5858(class_1297.java:1579)
	at knot//chronosacaria.mcdar.goals.FollowSummonerGoal.method_6266(FollowSummonerGoal.java:41)
	at knot//net.minecraft.class_4135.method_6266(class_4135.java:27)
	at knot//net.minecraft.class_1355.method_6275(class_1355.java:85)
	at knot//net.minecraft.class_1308.method_6023(class_1308.java:771)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:550)
	at knot//net.minecraft.class_1439.method_6007(class_1439.java:121)
	at knot//chronosacaria.mcdar.entities.GolemKitGolemEntity.method_6007(GolemKitGolemEntity.java:68)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: mcdar:golem_kit_golem (chronosacaria.mcdar.entities.GolemKitGolemEntity)
	Entity ID: 66672
	Entity Name: Golem Kit Golem
	Entity's Exact location: 20.60, 94.00, 93.27
	Entity's Block location: World: (20,94,93), Section: (at 4,14,13 in 1,5,5; chunk contains blocks 16,-64,80 to 31,639,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,639,511)
	Entity's Momentum: -0.04, -0.08, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Expected Behavior

The Entity should not be crashing the world.

### Mod Version

1.20.1

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Custom

**Comment by chronosacaria** [comment]
@jacobcrashout So remember how I said to post the whole crash report? I should have been clearer. Please upload the whole file. This is why I said to upload the whole log and not what seemed relevant, because I need your mod list and other information in that file

**Comment by jacobcrashout** [comment]
[crashreport.txt](https://github.com/user-attachments/files/18221037/crashreport.txt)

**Comment by jacobcrashout** [comment]
First time anyones ever asked for the whole thing and meant the whole thing lol, sorry for the confusion!

**Comment by chronosacaria** [comment]
@jacobcrashout No worries. That's not on you. I should have been clearer. Thanks for the file upload. I'll be taking a look at this tomorrow

**Comment by CaoTrongThang** [comment]
But is this fixed in the latest version?

**Comment by chronosacaria** [comment]
@CaoTrongThang Not yet. Once it is fixed, though, this issue will be closed. The issue you opened was the same issue that is here, so it was closed as a duplicate

**Comment by CaoTrongThang** [comment]
> [@CaoTrongThang](https://github.com/CaoTrongThang) Not yet. Once it is fixed, though, this issue will be closed. The issue you opened was the same issue that is here, so it was closed as a duplicate

Hi I'm back, is there any plan fixing this issue?, I wanna use the mod.

**Comment by jacobcrashout** [comment]
> > [@CaoTrongThang](https://github.com/CaoTrongThang) Not yet. Once it is fixed, though, this issue will be closed. The issue you opened was the same issue that is here, so it was closed as a duplicate
> 
> Hi I'm back, is there any plan fixing this issue?, I wanna use the mod.

I still use the mod even though I opened this Bug Report; if you do not use the iron golems the mod should work perfectly fine!

**Comment by chronosacaria** [comment]
> > [@CaoTrongThang](https://github.com/CaoTrongThang) Not yet. Once it is fixed, though, this issue will be closed. The issue you opened was the same issue that is here, so it was closed as a duplicate
> 
> Hi I'm back, is there any plan fixing this issue?, I wanna use the mod.

There is, of course, a plan to fix the issue; but, as stated in the comment below yours, in the meantime you can just avoid using the Golem Kit. In the latest development version, we've been unable to reproduce the issue; but more testing is needed

**Comment by ImNamzz** [comment]
I deleted the mod serverside, but the golem still seems to crash the game

**Comment by zvn570** [comment]
> > > [@CaoTrongThang](https://github.com/CaoTrongThang) Not yet. Once it is fixed, though, this issue will be closed. The issue you opened was the same issue that is here, so it was closed as a duplicate
> > 
> > 
> > Hi I'm back, is there any plan fixing this issue?, I wanna use the mod.
> 
> I still use the mod even though I opened this Bug Report; if you do not use the iron golems the mod should work perfectly fine!

Did you crash with other summon artifact? I know Llama and Iron Golem crashes server, but how about the Wolf, Sheep, and Bee artifacts?

**Comment by zvn570** [comment]
This bug seems to happen with all artifact that summons and it happens when you die while the summon is in world.

**Comment by 125dino** [comment]
On my server it crashed when a player with the iron golem spawned disconnected

**Comment by chronosacaria** [comment]
> This bug seems to happen with all artifact that summons and it happens when you die while the summon is in world.

So does it happen any time you die? I've been trying to reproduce this issue and I've not been able to do so consistently

**Comment by chronosacaria** [comment]
> On my server it crashed when a player with the iron golem spawned disconnected

So, just them logging out was enough to cause a crash?

**Comment by zvn570** [comment]
> > This bug seems to happen with all artifact that summons and it happens when you die while the summon is in world.
> 
> So does it happen any time you die? I've been trying to reproduce this issue and I've not been able to do so consistently

For me, it's also inconsistent. It happens when I die with summon in world, but only sometimes. However it tends to happen more when you die when the summon is attacking a entity.

**Comment by chronosacaria** [comment]
> > > This bug seems to happen with all artifact that summons and it happens when you die while the summon is in world.
> > 
> > So does it happen any time you die? I've been trying to reproduce this issue and I've not been able to do so consistently
> 
> For me, it's also inconsistent. It happens when I die with summon in world, but only sometimes. However it tends to happen more when you die when the summon is attacking a entity.

Ah, okay! This is incredible helpful! I think I know where the issue is that is causing the crash, then! If I can confirm this, I should be able to put out a patch for 1.20.1 to alleviate this issue. Thank you, so much!

**Comment by 125dino** [comment]
> > > This bug seems to happen with all artifact that summons and it happens when you die while the summon is in world.
> > 
> > 
> > So does it happen any time you die? I've been trying to reproduce this issue and I've not been able to do so consistently
> 
> For me, it's also inconsistent. It happens when I die with summon in world, but only sometimes. However it tends to happen more when you die when the summon is attacking a entity.

I agree, the player on my server had the iron golem attacking mobs when he logged out and it crashed. I haven't been able to do any testing, but will try to do some in the near future
