### ISSUE TITLE
[Bug Report]: Crash

### ISSUE THREAD

**Issue by CaoTrongThang** [chronosacaria/MCDungonesArtifacts#46]
### Describe the bug; What happened?

My and my friends were playing but suddenly crashed

I don't really know why, sorry very much

### Expected Behavior
I hope it won't crash

### Mod Version

4.0.4

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

1.20.1 modpack

### Additional context

I've the crashlog here

`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_19538()" because "$$0" is null
	at knot//net.minecraft.class_1297.method_5858(class_1297.java:1579)
	at knot//chronosacaria.mcdar.goals.FollowSummonerGoal.method_6266(FollowSummonerGoal.java:41)
	at knot//net.minecraft.class_4135.method_6266(class_4135.java:27)
	at knot//net.minecraft.class_1355.method_6275(class_1355.java:85)
	at knot//net.minecraft.class_1308.method_6023(class_1308.java:771)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:550)
	at knot//net.minecraft.class_1296.method_6007(class_1296.java:128)
	at knot//net.minecraft.class_1429.method_6007(class_1429.java:58)
	at knot//net.minecraft.class_1496.method_6007(class_1496.java:580)
	at knot//net.minecraft.class_3986.method_6007(class_3986.java:81)
	at knot//chronosacaria.mcdar.entities.WonderfulWheatLlamaEntity.method_6007(WonderfulWheatLlamaEntity.java:77)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//net.minecraft.class_1496.method_5773(class_1496.java:621)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by chronosacaria** [comment]
Duplicate issue. See #45
