### ISSUE TITLE
mcda & mcdar throws exception

### ISSUE THREAD

**Issue by Yucked** [chronosacaria/MCDungonesArtifacts#5]
Happens with both of these mods:
- https://www.curseforge.com/minecraft/mc-mods/mcda
- https://www.curseforge.com/minecraft/mc-mods/mcdar

```
[18:26:33] [main/WARN]: Catching java.lang.ClassNotFoundException: net/minecraft/class_970
java.lang.ClassNotFoundException: net/minecraft/class_970
        at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [launcher.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [launcher.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) [?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [launcher.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [launcher.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [launcher.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [launcher.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [launcher.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [launcher.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [launcher.jar:?]
[18:26:33] [main/WARN]: Error loading class: net/minecraft/class_970 (java.lang.ClassNotFoundException: net/minecraft/class_970)
```

**Comment by chronosacaria** [comment]
@Yucked Without the whole crash report I can only speculate, but since it is happening with both of them I can only imagine that you don't have Cloth Config API installed. Can you confirm whether this is the case or not?

**Comment by Yucked** [comment]
No, that isn't the case. I do have Cloth Config API installed (5.1.4.0). The exception doesn't crash the server though but happens every time I start the server up.

**Comment by chronosacaria** [comment]
Oh okay. Can you provide the whole crash log please?

**Comment by Yucked** [comment]
Don't really see any crash reports directory or file but I've attached the latest log file
[latest.log](https://github.com/chronosacaria/MCDungeonsArtifacts/files/7541749/latest.log)

These 2 lines:
```
[15:21:21] [main/WARN]: @Mixin target net.minecraft.class_970 was not found mcda.mixins.json:ArmorFeatureRendererMixin
[15:21:21] [main/WARN]: @Mixin target net.minecraft.class_757 was not found mcdar.mixins.json:GameRendererMixin
```

**Comment by chronosacaria** [comment]
That is really strange. I am unpacking and should have access to my computer tomorrow. I can check the log then. Sorry for the wait. Thanks for the log in the meantime

**Comment by Yucked** [comment]
No worries! Thanks so much 🙏

**Comment by chronosacaria** [comment]
Sorry this is taking so long, @Yucked. My case for my computer is borked so I can't turn my computer on without shorting out the pins manually. I hope to have this fixed on Monday so I should be able to look at this issue soon. Just wanted to let you know that it is still on my radar

**Comment by Yucked** [comment]
No worries my mans. Error isn't of high importance so take your time.

**Comment by HixxyDubz** [comment]
i have cloth api installed too, sorry for the delayed reply, is there anything i can help test for you to help determine the issue?
